In [ ]:
import warnings

warnings.filterwarnings( 'ignore' )

In [2]:
import pandas as pd

number_of_sample_users = 5000

file_name = 'rand_grad5_2k.txt'

try:
    ex_rating_df = pd.read_table('C:\\content_caching\\'+file_name, sep=' ', header=None)
except:
    ex_rating_df = pd.read_csv('/content/drive/MyDrive/jaesungpark_lab/Paper_review/Content_Caching/'+file_name)

ex_rating_df

0         1         2         3         4         5         6    \
0       0.134154  0.541440  0.884019  0.532107  0.855771  0.250896  0.749662   
1       0.565347  0.516139  0.972831  0.557045  0.667992  0.277072  0.429763   
2       0.142153  0.085115  0.201071  0.387497  0.738605  0.574894  0.053932   
3       0.297127  0.747975  0.935343  0.592261  0.734072  0.504719  0.329421   
4       0.431544  0.635911  0.191388  0.909202  0.896246  0.105064  0.179520   
...          ...       ...       ...       ...       ...       ...       ...   
319995  0.239466  0.244757  0.739386  0.111383  0.330154  0.579245  0.368840   
319996  0.406479  0.417341  0.184774  0.259103  0.570069  0.822974  0.178998   
319997  0.938750  0.036392  0.725376  0.911077  0.612368  0.412170  0.932528   
319998  0.797117  0.646020  0.425576  0.645762  0.299168  0.519217  0.195605   
319999  0.893903  0.772089  0.789392  0.106060  0.527043  0.264974  0.449975   

             7         8         9    ...       119       120       121  \
0       0.030124  0.174822  0.551611  ...  0.446782  0.532038  0.271780   
1       0.714360  0.834694  0.038690  ...  0.859676  0.251141  0.951163   
2       0.408686  0.899615  0.042655  ...  0.441721  0.161174  0.283790   
3       0.211416  0.586863  0.031987  ...  0.274423  0.506168  0.481894   
4       0.887643  0.787695  0.343452  ...  0.678870  0.315081  0.787248   
...          ...       ...       ...  ...       ...       ...       ...   
319995  0.914743  0.646432  0.255453  ...  0.587461  0.266125  0.560812   
319996  0.451635  0.194337  0.785723  ...  0.490914  0.537342  0.246477   
319997  0.754248  0.815463  0.916184  ...  0.021768  0.240970  0.854112   
319998  0.048821  0.450491  0.301919  ...  0.860365  0.699625  0.857813   
319999  0.541176  0.674753  0.622009  ...  0.490776  0.804059  0.685495   

             122       123       124       125       126       127  128  
0       0.698809  0.123099  0.443782  0.335374  0.228386  0.257891  NaN  
1       0.476250  0.929771  0.292965  0.361534  0.019937  0.478134  NaN  
2       0.930169  0.087778  0.102103  0.662459  0.220412  0.303970  NaN  
3       0.883439  0.160665  0.295778  0.578569  0.100302  0.332303  NaN  
4       0.135754  0.427234  0.267912  0.330518  0.652415  0.521198  NaN  
...          ...       ...       ...       ...       ...       ...  ...  
319995  0.076594  0.467894  0.778350  0.734616  0.860765  0.384362  NaN  
319996  0.390240  0.709207  0.269866  0.414482  0.933741  0.661906  NaN  
319997  0.322356  0.798724  0.540485  0.828066  0.899139  0.622652  NaN  
319998  0.176690  0.968148  0.690782  0.335623  0.053978  0.882276  NaN  
319999  0.730868  0.503823  0.510012  0.059219  0.563928  0.679054  NaN  

[320000 rows x 129 columns]

In [3]:
try:
    ex_rating_df = ex_rating_df.drop(128, axis=1)
except:
    print('No index column')

ex_rating_df

0         1         2         3         4         5         6    \
0       0.134154  0.541440  0.884019  0.532107  0.855771  0.250896  0.749662   
1       0.565347  0.516139  0.972831  0.557045  0.667992  0.277072  0.429763   
2       0.142153  0.085115  0.201071  0.387497  0.738605  0.574894  0.053932   
3       0.297127  0.747975  0.935343  0.592261  0.734072  0.504719  0.329421   
4       0.431544  0.635911  0.191388  0.909202  0.896246  0.105064  0.179520   
...          ...       ...       ...       ...       ...       ...       ...   
319995  0.239466  0.244757  0.739386  0.111383  0.330154  0.579245  0.368840   
319996  0.406479  0.417341  0.184774  0.259103  0.570069  0.822974  0.178998   
319997  0.938750  0.036392  0.725376  0.911077  0.612368  0.412170  0.932528   
319998  0.797117  0.646020  0.425576  0.645762  0.299168  0.519217  0.195605   
319999  0.893903  0.772089  0.789392  0.106060  0.527043  0.264974  0.449975   

             7         8         9    ...       118       119       120  \
0       0.030124  0.174822  0.551611  ...  0.428548  0.446782  0.532038   
1       0.714360  0.834694  0.038690  ...  0.240802  0.859676  0.251141   
2       0.408686  0.899615  0.042655  ...  0.121951  0.441721  0.161174   
3       0.211416  0.586863  0.031987  ...  0.298760  0.274423  0.506168   
4       0.887643  0.787695  0.343452  ...  0.023382  0.678870  0.315081   
...          ...       ...       ...  ...       ...       ...       ...   
319995  0.914743  0.646432  0.255453  ...  0.597907  0.587461  0.266125   
319996  0.451635  0.194337  0.785723  ...  0.704480  0.490914  0.537342   
319997  0.754248  0.815463  0.916184  ...  0.112815  0.021768  0.240970   
319998  0.048821  0.450491  0.301919  ...  0.869393  0.860365  0.699625   
319999  0.541176  0.674753  0.622009  ...  0.116651  0.490776  0.804059   

             121       122       123       124       125       126       127  
0       0.271780  0.698809  0.123099  0.443782  0.335374  0.228386  0.257891  
1       0.951163  0.476250  0.929771  0.292965  0.361534  0.019937  0.478134  
2       0.283790  0.930169  0.087778  0.102103  0.662459  0.220412  0.303970  
3       0.481894  0.883439  0.160665  0.295778  0.578569  0.100302  0.332303  
4       0.787248  0.135754  0.427234  0.267912  0.330518  0.652415  0.521198  
...          ...       ...       ...       ...       ...       ...       ...  
319995  0.560812  0.076594  0.467894  0.778350  0.734616  0.860765  0.384362  
319996  0.246477  0.390240  0.709207  0.269866  0.414482  0.933741  0.661906  
319997  0.854112  0.322356  0.798724  0.540485  0.828066  0.899139  0.622652  
319998  0.857813  0.176690  0.968148  0.690782  0.335623  0.053978  0.882276  
319999  0.685495  0.730868  0.503823  0.510012  0.059219  0.563928  0.679054  

[320000 rows x 128 columns]

In [4]:
# Normalize each row(=each mecs)
ex_rating_df = ex_rating_df.div(ex_rating_df.max(axis=1), axis=0)
ex_rating_df

0         1         2         3         4         5         6    \
0       0.135268  0.545936  0.891360  0.536526  0.862878  0.252980  0.755887   
1       0.565612  0.516381  0.973287  0.557306  0.668305  0.277202  0.429965   
2       0.144500  0.086521  0.204391  0.393896  0.750802  0.584387  0.054823   
3       0.297305  0.748423  0.935903  0.592615  0.734511  0.505021  0.329618   
4       0.435557  0.641825  0.193168  0.917657  0.904581  0.106041  0.181189   
...          ...       ...       ...       ...       ...       ...       ...   
319995  0.242363  0.247718  0.748331  0.112730  0.334148  0.586252  0.373302   
319996  0.408204  0.419112  0.185558  0.260202  0.572488  0.826466  0.179757   
319997  0.945231  0.036643  0.730384  0.917366  0.616595  0.415015  0.938966   
319998  0.797644  0.646447  0.425857  0.646189  0.299366  0.519560  0.195734   
319999  0.924504  0.798520  0.816415  0.109691  0.545085  0.274045  0.465379   

             7         8         9    ...       118       119       120  \
0       0.030374  0.176274  0.556192  ...  0.432107  0.450492  0.536456   
1       0.714695  0.835086  0.038708  ...  0.240915  0.860079  0.251259   
2       0.415435  0.914471  0.043359  ...  0.123965  0.449015  0.163836   
3       0.211543  0.587214  0.032006  ...  0.298939  0.274587  0.506471   
4       0.895898  0.795020  0.346646  ...  0.023599  0.685183  0.318011   
...          ...       ...       ...  ...       ...       ...       ...   
319995  0.925809  0.654252  0.258543  ...  0.605140  0.594568  0.269344   
319996  0.453551  0.195162  0.789057  ...  0.707469  0.492997  0.539622   
319997  0.759455  0.821092  0.922509  ...  0.113594  0.021918  0.242633   
319998  0.048853  0.450789  0.302119  ...  0.869968  0.860934  0.700088   
319999  0.559702  0.697852  0.643302  ...  0.120644  0.507577  0.831584   

             121       122       123       124       125       126       127  
0       0.274037  0.704612  0.124121  0.447467  0.338159  0.230283  0.260033  
1       0.951609  0.476473  0.930207  0.293102  0.361704  0.019946  0.478358  
2       0.288476  0.945529  0.089228  0.103789  0.673398  0.224052  0.308990  
3       0.482182  0.883968  0.160761  0.295955  0.578915  0.100362  0.332502  
4       0.794569  0.137016  0.431207  0.270403  0.333592  0.658482  0.526045  
...          ...       ...       ...       ...       ...       ...       ...  
319995  0.567596  0.077521  0.473554  0.787766  0.743503  0.871178  0.389012  
319996  0.247523  0.391896  0.712216  0.271011  0.416241  0.937703  0.664714  
319997  0.860008  0.324581  0.804238  0.544216  0.833782  0.905346  0.626950  
319998  0.858380  0.176807  0.968788  0.691239  0.335845  0.054014  0.882860  
319999  0.708962  0.755888  0.521070  0.527471  0.061246  0.583233  0.702300  

[320000 rows x 128 columns]

In [5]:
import numpy as np

image_array = np.array(ex_rating_df)
image_array.shape

(320000, 128)

In [6]:
number_of_mecs = 16
number_of_images = image_array.shape[0] // number_of_mecs

print('number of mecs : ', number_of_mecs)
print('number of images : ', number_of_images)

number of mecs :  16
number of images :  20000


In [7]:
import os

save_path = './'+file_name[:-4] # 확장자 제외

try:
    os.mkdir(save_path)
except:
    print('[Errno 17] File exists')

In [8]:
from PIL import Image


for i in range(number_of_images):
    print(i,' 번째 이미지 생성중 ...')
    image = image_array[i:i+number_of_mecs, :]
    print(image.shape)    # Create a PIL image from the array
    #print(image)

    image = Image.fromarray((255 * image).astype(np.uint8), mode='L')

    file_name = '/train'+str(i)+'.png'
    image.save(save_path+file_name)


0  번째 이미지 생성중 ...
(16, 128)
1  번째 이미지 생성중 ...
(16, 128)
2  번째 이미지 생성중 ...
(16, 128)
3  번째 이미지 생성중 ...
(16, 128)
4  번째 이미지 생성중 ...
(16, 128)
5  번째 이미지 생성중 ...
(16, 128)
6  번째 이미지 생성중 ...
(16, 128)
7  번째 이미지 생성중 ...
(16, 128)
8  번째 이미지 생성중 ...
(16, 128)
9  번째 이미지 생성중 ...
(16, 128)
10  번째 이미지 생성중 ...
(16, 128)
11  번째 이미지 생성중 ...
(16, 128)
12  번째 이미지 생성중 ...
(16, 128)
13  번째 이미지 생성중 ...
(16, 128)
14  번째 이미지 생성중 ...
(16, 128)
15  번째 이미지 생성중 ...
(16, 128)
16  번째 이미지 생성중 ...
(16, 128)
17  번째 이미지 생성중 ...
(16, 128)
18  번째 이미지 생성중 ...
(16, 128)
19  번째 이미지 생성중 ...
(16, 128)
20  번째 이미지 생성중 ...
(16, 128)
21  번째 이미지 생성중 ...
(16, 128)
22  번째 이미지 생성중 ...
(16, 128)
23  번째 이미지 생성중 ...
(16, 128)
24  번째 이미지 생성중 ...
(16, 128)
25  번째 이미지 생성중 ...
(16, 128)
26  번째 이미지 생성중 ...
(16, 128)
27  번째 이미지 생성중 ...
(16, 128)
28  번째 이미지 생성중 ...
(16, 128)
29  번째 이미지 생성중 ...
(16, 128)
30  번째 이미지 생성중 ...
(16, 128)
31  번째 이미지 생성중 ...
(16, 128)
32  번째 이미지 생성중 ...
(16, 128)
33  번째 이미지 생성중 ...
(16, 128)
34  번째 이미지 생성중 ...
(16, 

In [9]:
from IPython.display import display
from PIL import Image

# Set up the path to the saved image
file_name = '/train'+str(0)+'.png'


# Load the image
image = Image.open(save_path+file_name)

# Display the image
display(image)

In [10]:
import numpy as np

image_array = np.array(image)
image_array.shape

(16, 128)

In [11]:
for i in range(1):
    file_name = '/train'+str(i)+'.png'

    # Load the image
    print(save_path+file_name)
    image = Image.open(save_path+file_name)

    image_array = np.array(image)

    for row in range(image_array.shape[0]):
        print(image_array[row].sum())
    print('ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ')
    print(image_array)

./rand_grad5_2k/train0.png
15865
16805
15591
15873
16894
16668
16012
15040
16741
16645
16241
16247
16823
15521
16348
15930
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
[[ 34 139 227 ...  86  58  66]
 [144 131 248 ...  92   5 121]
 [ 36  22  52 ... 171  57  78]
 ...
 [230 171   5 ... 204  49 184]
 [ 10  71 226 ... 171 125 184]
 [142  21  83 ... 158 248 211]]
